services:
  mssql:
    container_name: ms-sql-server
    hostname: ms-sql-server
    #image: mcr.microsoft.com/azure-sql-edge
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_USER: 'SA' 
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    labels:
      # Enable Traefik and network
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # TCP
      - "traefik.tcp.routers.mssql.rule=HostSNI(`mivne-db.localhost`)"
      - "traefik.tcp.routers.mssql.service=mssql"
      - "traefik.tcp.routers.mssql.entrypoints=mssql-tcp"
      - "traefik.tcp.services.mssql.loadbalancer.server.port=1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./backups:/var/opt/mssql/backups
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true 
      